== Cheshire Cats

=== Chapter 6 (an excerpt)

There was certainly too much of it in the air. Even the Duchess sneezed occasionally; and as for the baby, it was sneezing and howling alternately without a moment’s pause. The only things in the kitchen that did not sneeze, were the cook, and a large cat which was sitting on the hearth and grinning from ear to ear.

‘Please would you tell me,’ said Alice, a little timidly, for she was not quite sure whether it was good manners for her to speak first, ‘why your cat grins like that?’

‘It’s a Cheshire cat,’ said the Duchess, ‘and that’s why. Pig!’

She said the last word with such sudden violence that Alice quite jumped; but she saw in another moment that it was addressed to the baby, and not to her, so she took courage, and went on again:—

‘I didn’t know that Cheshire cats always grinned; in fact, I didn’t know that cats could grin.’

‘They all can,’ said the Duchess; ‘and most of ’em do.’

‘I don’t know of any that do,’ Alice said very politely, feeling quite pleased to have got into a conversation.

‘You don’t know much,’ said the Duchess; ‘and that’s a fact.’

Alice did not at all like the tone of this remark, and thought it would be as well to introduce some other subject of conversation. 