== Cheshire Cats

=== Chapter 6 (an excerpt)

There was certainly too much of it in the air. Even the Duchess sneezed occasionally; and as for the baby, it was sneezing and howling alternately without a moment’s pause. The only things in the kitchen that did not sneeze, were the cook, and a large cat which was sitting on the hearth and grinning from ear to ear.

‘Please would you tell me,’ said Alice, a little timidly, for she was not quite sure whether it was good manners for her to speak first, ‘why your cat grins like that?’

‘It’s a Cheshire cat,’ said the Duchess, ‘and that’s why. Pig!’

She said the last word with such sudden violence that Alice quite jumped; but she saw in another moment that it was addressed to the baby, and not to her, so she took courage, and went on again:—

‘I didn’t know that Cheshire cats always grinned; in fact, I didn’t know that cats could grin.’

‘They all can,’ said the Duchess; ‘and most of ’em do.’

‘I don’t know of any that do,’ Alice said very politely, feeling quite pleased to have got into a conversation.

‘You don’t know much,’ said the Duchess; ‘and that’s a fact.’

Alice did not at all like the tone of this remark, and thought it would be as well to introduce some other subject of conversation. While she was trying to fix on one, the cook took the cauldron of soup off the fire, and at once set to work throwing everything within her reach at the Duchess and the baby — the fire-irons came first; then followed a shower of saucepans, plates, and dishes. The Duchess took no notice of them even when they hit her; and the baby was howling so much already, that it was quite impossible to say whether the blows hurt it or not.

‘Oh, please mind what you’re doing!’ cried Alice, jumping up and down in an agony of terror. ‘Oh, there goes his precious nose’; as an unusually large saucepan flew close by it, and very nearly carried it off.

‘If everybody minded their own business,’ the Duchess said in a hoarse growl, ‘the world would go round a deal faster than it does.’

‘Which would not be an advantage,’ said Alice, who felt very glad to get an opportunity of showing off a little of her knowledge. ‘Just think of what work it would make with the day and night! You see the earth takes twenty-four hours to turn round on its axis —’

‘Talking of axes,’ said the Duchess, ‘chop off her head!’

=== Chapter 8 (an excerpt)

She was looking about for some way of escape, and wondering whether she could get away without being seen, when she noticed a curious appearance in the air: it puzzled her very much at first, but, after watching it a minute or two, she made it out to be a grin, and she said to herself ‘It’s the Cheshire Cat: now I shall have somebody to talk to.’

‘How are you getting on?’ said the Cat, as soon as there was mouth enough for it to speak with.

Alice waited till the eyes appeared, and then nodded. ‘It’s no use speaking to it,’ she thought, ‘till its ears have come, or at least one of them.’ In another minute the whole head appeared, and then Alice put down her flamingo, and began an account of the game, feeling very glad she had someone to listen to her. The Cat seemed to think that there was enough of it now in sight, and no more of it appeared.

‘I don’t think they play at all fairly,’ Alice began, in rather a complaining tone, ‘and they all quarrel so dreadfully one can’t hear oneself speak — and they don’t seem to have any rules in particular; at least, if there are, nobody attends to them — and you’ve no idea how confusing it is all the things being alive; for instance, there’s the arch I’ve got to go through next walking about at the other end of the ground — and I should have croqueted the Queen’s hedgehog just now, only it ran away when it saw mine coming!’

‘How do you like the Queen?’ said the Cat in a low voice.

‘Not at all,’ said Alice: ‘she’s so extremely —’ Just then she noticed that the Queen was close behind her, listening: so she went on, ‘— likely to win, that it’s hardly worth while finishing the game.’

The Queen smiled and passed on.

‘Who are you talking to?’ said the King, going up to Alice, and looking at the Cat’s head with great curiosity.

‘It’s a friend of mine — a Cheshire Cat,’ said Alice: ‘allow me to introduce it.’

‘I don’t like the look of it at all,’ said the King: ‘however, it may kiss my hand if it likes.’

‘I’d rather not,’ the Cat remarked.

‘Don’t be impertinent,’ said the King, ‘and don’t look at me like that!’ He got behind Alice as he spoke.

‘A cat may look at a king,’ said Alice. ‘I’ve read that in some book, but I don’t remember where.’

‘Well, it must be removed,’ said the King very decidedly, and he called the Queen, who was passing at the moment, ‘My dear! I wish you would have this cat removed!’

The Queen had only one way of settling all difficulties, great or small. ‘Off with his head!’ she said, without even looking round.

‘I’ll fetch the executioner myself,’ said the King eagerly, and he hurried off.

Alice thought she might as well go back, and see how the game was going on, as she heard the Queen’s voice in the distance, screaming with passion. She had already heard her sentence three of the players to be executed for having missed their turns, and she did not like the look of things at all, as the game was in such confusion that she never knew whether it was her turn or not. So she went in search of her hedgehog.

The hedgehog was engaged in a fight with another hedgehog, which seemed to Alice an excellent opportunity for croqueting one of them with the other: the only difficulty was, that her flamingo was gone across to the other side of the garden, where Alice could see it trying in a helpless sort of way to fly up into a tree.

By the time she had caught the flamingo and brought it back, the fight was over, and both the hedgehogs were out of sight: ‘but it doesn’t matter much,’ thought Alice, ‘as all the arches are gone from this side of the ground.’ So she tucked it away under her arm, that it might not escape again, and went back for a little more conversation with her friend.

When she got back to the Cheshire Cat, she was surprised to find quite a large crowd collected round it: there was a dispute going on between the executioner, the King, and the Queen, who were all talking at once, while all the rest were quite silent, and looked very uncomfortable.

The moment Alice appeared, she was appealed to by all three to settle the question, and they repeated their arguments to her, though, as they all spoke at once, she found it very hard indeed to make out exactly what they said.