= Asciidoctor Extensions Lab
:idprefix:
:idseparator: -

A repository of sample and incubating Ruby-based extensions for Asciidoctor.

If you just want to use the extensions here, skip ahead to <<using-an-extension>>.
To create your own extension, we recommend that you first read the http://asciidoctor.org/docs/user-manual/#extensions[extensions section] in the Asciidoctor user manual.

== Extension types

We have these types of extensions in the lab:

- Preprocessor
- Treeprocessor
- Postprocessor
- BlockProcessor
- BlockMacroProcessor
- InlineMacroProcessor
- IncludeProcessor

The type of extension is always used in the name of the extension load file and directory to make it easy to distinguish.
You can also look for examples using `git grep`.
For example, to look for a `BlockMacroProcessor`, run the following command:

  $ git grep BlockMacroProcessor lib/

You will get a result like this:

....
lib/chart-block-macro/extension.rb:class ChartBlockMacro < Extensions::BlockMacroProcessor
lib/gist-block-macro/extension.rb:class GistBlockMacro < Extensions::BlockMacroProcessor
lib/pass-block-macro/extension.rb:class PassBlockMacro < Extensions::BlockMacroProcessor
lib/tree-block-macro/extension.rb:class TreeBlockMacro < Asciidoctor::Extensions::BlockMacroProcessor
....

== Extension files

Each extension consists of several files:

- A file that registers the extension (sometimes also contains the extension)
- A file with the extension itself (when not defined in the registration file)
- A file with sample AsciiDoc source to use to test the section
- Auxiliary assets needed by the extension

For example, the emoji-inline-macro extension has four files:

- https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/emoji-inline-macro.rb[lib/emoji-inline-macro.rb] (registration file)
- https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/emoji-inline-macro/extension.rb[lib/emoji-inline-macro/extension.rb] (extension file)
- https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/emoji-inline-macro/sample.adoc[lib/emoji-inline-macro/sample.adoc] (sample AsciiDoc file)
- https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/emoji-inline-macro/twemoji-awesome.css[lib/emoji-inline-macro/twemoji-awesome.css] (auxiliary asset file)

NOTE: The registration file (e.g., emoji-inline-macro.rb) goes in the [path]_lib_ directory whereas the remaining files go inside a directory whose base name matches the name of the registration file (e.g., emoji-inline-macro).

== Using an extension

Before create your own extensions, it would be wise to run one yourself.
First, make sure Asciidoctor is installed:

 $ gem install asciidoctor

Next, we'll run an extension from the root directory of the project:

  $ asciidoctor -r lib/emoji-inline-macro.rb lib/emoji-inline-macro/sample.adoc
  # asciidoctor: FAILED: 'lib/emoji-inline-macro.rb' could not be loaded
  # Use --trace for backtrace

Oops!
We forgot to include the leading `./` when using the `-r` flag
Let's try again:

  $ asciidoctor -r ./lib/emoji-inline-macro.rb lib/emoji-inline-macro/sample.adoc

All right, it ran!
The output file, [path]_sample.html_, was created in the same directory as the source file, [path]_sample.adoc_.

The relevant bits of the input and output are show below.

._lib/emoji-inline-macro/sample.adoc_
```asciidoc
Faster than a emoji:turtle[1x]!

This is an example of how you can emoji:heart[lg] Asciidoctor and Twitter Emoji.
```

._lib/emoji-inline-macro/sample.html_
```html
<div class="paragraph">
<p>Faster than a <i class="twa twa-1x twa-turtle"></i>!</p>
</div>
<div class="paragraph">
<p>This is an example of how you can <i class="twa twa-lg twa-heart"></i> Asciidoctor and Twitter Emoji.</p>
</div>
```

WARNING: Certain extensions require additional libraries.
Please consult the registration file for the extension for details about what is required to use it.

== Adding an extension

https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/44[TODO].

== Other extensions

See http://asciidoctor.org/docs/extensions/[this list] of extensions for Asciidoctor.

////
== Transpiling extensions for Asciidoctor.js

https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/44[TODO].
////
